# Generated by Django 4.2.11 on 2024-05-27 11:02

from django.db import migrations, models
import django.db.models.deletion
import month.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, verbose_name='Наименование компании')),
                ('name_full', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('contact', models.TextField(verbose_name='Контакты')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('note', models.TextField(verbose_name='Примечания')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadachnik.company')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='ContractLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=70)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('term', models.CharField(max_length=30)),
                ('total_sum', models.FloatField()),
                ('pay_f_month', models.FloatField()),
                ('pay_f_day', models.FloatField()),
                ('relevant', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Договор аренды/субаренды',
                'verbose_name_plural': 'Договоры аренды/субаренды',
            },
        ),
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('esk', models.CharField(max_length=10)),
                ('inn', models.CharField(max_length=20)),
                ('kpp', models.CharField(max_length=20)),
                ('kd', models.CharField(max_length=100)),
                ('mm_contract', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='EBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('article', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NDFL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PayTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, verbose_name='Наименование подразделения')),
                ('name_full', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('contact', models.TextField(verbose_name='Контакты')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('note', models.TextField(verbose_name='Примечания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadachnik.company', verbose_name='Компания')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadachnik.subdivision')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('period', month.models.MonthField(help_text='Выберите месяц', verbose_name='Month Value')),
                ('pay_day', models.DateField()),
                ('pfm', models.CharField(default='Главный маркшейдер', max_length=30)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.contractlease')),
                ('counter_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.counterparty')),
                ('ebk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.ebk')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadachnik.object')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='LicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('project', models.ManyToManyField(to='zadachnik.project')),
            ],
            options={
                'verbose_name': 'Лицензионный участок',
                'verbose_name_plural': 'Лицензионные участки',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('lic_area', models.ManyToManyField(to='zadachnik.licarea')),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
            },
        ),
        migrations.AddField(
            model_name='contractlease',
            name='counter_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.counterparty'),
        ),
        migrations.AddField(
            model_name='contractlease',
            name='ndfl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.ndfl'),
        ),
        migrations.AddField(
            model_name='contractlease',
            name='nds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.nds'),
        ),
        migrations.AddField(
            model_name='contractlease',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.payterm'),
        ),
    ]
