# Generated by Django 4.2.11 on 2024-05-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zadachnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebk',
            options={'verbose_name': 'ЕБК', 'verbose_name_plural': 'ЕБК'},
        ),
        migrations.AlterModelOptions(
            name='ndfl',
            options={'verbose_name': 'НДФЛ', 'verbose_name_plural': 'НДФЛ'},
        ),
        migrations.AlterModelOptions(
            name='nds',
            options={'verbose_name': 'НДС', 'verbose_name_plural': 'НДС'},
        ),
        migrations.AlterModelOptions(
            name='payterm',
            options={'verbose_name': 'Условие платежа', 'verbose_name_plural': 'Условия платежа'},
        ),
        migrations.AlterModelOptions(
            name='rentpayment',
            options={'verbose_name': 'Платеж по аренде', 'verbose_name_plural': 'Платежи по аренде'},
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='counter_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='date_begin',
            field=models.DateField(verbose_name='Дата начала договора'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания договора'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='ndfl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.ndfl', verbose_name='НДФЛ'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='nds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.nds', verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='number',
            field=models.CharField(max_length=70, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='pay_f_day',
            field=models.FloatField(verbose_name='Платеж в день'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='pay_f_month',
            field=models.FloatField(verbose_name='Платеж в месяц'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zadachnik.payterm', verbose_name='Условие платежа'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='relevant',
            field=models.BooleanField(verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='term',
            field=models.CharField(max_length=30, verbose_name='Срок действия договора'),
        ),
        migrations.AlterField(
            model_name='contractlease',
            name='total_sum',
            field=models.FloatField(verbose_name='Общая сумма договора'),
        ),
    ]
